const weeklyMenu = {
    Sunday: {
        lunch: [
            "Bhandara Aloo",
            "Veg Tawa Dry",
            "Puri",
            "Moong Dal Tadka",
            "Plane Rice",
            "Salad (Cucumber, Carrot, Onion)",
            "Fry Papad",
            "Boondi Raita",
        ],
        dinner: [
            "Avial",
            "Lauki + Chana Dal Fry",
            "Chapati",
            "Dal Fry",
            "Rice",
            "Veg Hot and Sour",
            "Curd, Pickle",
            "Papad",
        ],
    },
    Monday: {
        lunch: [
            "Chana Masala",
            "Cabbage Tomato",
            "Chapati",
            "Dal Tadka",
            "Rice / Jeera Rice",
            "Salad (Cucumber, Carrot, Onion)",
            "Roasted Papad",
            "Curd, Pickle",
        ],
        dinner: [
            "Shahi Paneer",
            "Gajar Methi",
            "Chapati",
            "Dal Panchratna",
            "Rice",
            "Pumpkin + Carrot",
            "Raita",
            "Fry Papad",
        ],
    },
    Tuesday: {
        lunch: [
            "Veg Shahi Kurma",
            "Bhendi Fry",
            "Chapati",
            "Dal Fry",
            "Rice",
            "Rosted Papad",
            "Curd, Pickle",
            "Salad",
        ],
        dinner: [
            "Veg Jalfrezi",
            "Baigan Bharela",
            "Chapati",
            "Masoor Dal",
            "Rice",
            "Tomato Soup",
            "Curd, Pickle",
            "Fry Papad",
        ],
    },
    Wednesday: {
        lunch: [
            "Veg Kolhapuri",
            "Gobi Mutter Dry",
            "Paratha",
            "Moong Dal Fry",
            "Plane Rice",
            "Salad (Cucumber, Carrot, Onion)",
            "Fryums",
            "Curd, Pickle",
        ],
        dinner: [
            "Methi Malai Matar",
            "Beetroot Poriyal",
            "Chapati",
            "Mix Dal",
            "Rice",
            "Lemon Corriander Soup",
            "Curd, Pickle",
            "Rosted Papad",
        ],
    },
    Thursday: {
        lunch: [
            "Chole Bhature",
            "Mixed Veg Dry",
            "Bhature",
            "Dal Makhani",
            "Peas Pulao",
            "Salad (Cucumber, Carrot, Onion)",
            "Papad",
            "Raita",
        ],
        dinner: [
            "Veg Hyderabadi Masala",
            "Matki Aloo Dry",
            "Chapati",
            "Moong Dal Fry",
            "Rice",
            "Veg Minestrone",
            "Raita",
            "Papad",
        ],
    },
    Friday: {
        lunch: [
            "Rajma Masala",
            "Beans + Coconut Dry",
            "Chapati",
            "Dal Tadka",
            "Plane Rice",
            "Salad (Cucumber, Carrot, Onion)",
            "Rosted Papad",
            "Curd",
        ],
        dinner: [
            "Soyabean Masala",
            "Bhendi Do Payza",
            "Chapati",
            "Dalma",
            "Rice",
            "Veg Manchao",
            "Curd",
            "Papad",
        ],
    },
    Saturday: {
        lunch: [
            "Rice / Chapati",
            "Dal Makhani",
            "Veg Kurma",
            "Curd",
            "Papad & Salad",
            "Mango"
        ],
        dinner: [
            "Tamarind Rice",
            "Aloo Bhaji",
            "Roti",
            "Soup",
            "Sweet Dish",
            "Masala Chaas"
        ]
    },

};

export default weeklyMenu